export const HOST_CRYPTO = {
  bitcoin: 'bitcoin',
  ethereum: 'ethereum'
}

export const COIN_IMAGE = {
  CUSDC98: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/CUSDC98.png',
  BTC: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/BTC.png',
  ETH: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ETH.png',
  ETHARB: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/arbitrum_eth.png',
  ETHA0X: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/arbitrum_xdai.png',
  OP: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/op.png',
  BOBA: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/boba_eth.png',
  KCS: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/kucoin.png',
  BNB: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/BNBVer2.png',
  HT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/heco.png',
  TOMO: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/Tomo.png',
  USDT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/USDT.png',
  AVAX: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/avax.png',
  KSM: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/kusama.png',
  NEAR: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/near.png',
  DOT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/dot.png',
  C98: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/coin98.png',
  TRX: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/tron.png',
  CELO: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/celo.png',
  SOL: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/solana.jpg',
  SRM: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/serum.jpg',
  ATOM: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/cosmos.png',
  RUNE: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/thor.png',
  LUNA: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/terra.png',
  LUNA2: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/terra2.png',
  KAVA: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/kava.png',
  SCRT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/secretNetwork.png',
  EGLD: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/elrond.png',
  XTZ: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/tezos.png',
  ONE: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/harmony.png',
  CFX: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/conflux.png',
  AURORA: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/aurora.png',

  BAND: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/band.png',
  FTM: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/fantom.png',
  MATIC: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/polygon.png',
  XPRT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/persistance.png',
  XDAI: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_xdai.png',
  KAI: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_kardia.png',
  RON: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_ronin.png',
  OKT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_okex.png',
  GT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_gate.png',
  KLAY: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_klaytn.png',

  CRO: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/CRO.png',
  BTT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/BTT.png',
  HNT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_hnt.png',
  FLOW: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_flow.png',
  THETA: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/THETA.png',
  GLMR: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/GMLR.png',
  LAT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/LAT.png',
  TON: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/TON.png',
  TFUEL: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/TFUEL.png',
  ALGO: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/algorand.png',
  CSPR: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/casper.png',
  FX: 'https://coin98.s3.ap-southeast-1.amazonaws.com/fx.png',
  APT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/aptos.jpg',
  SUI: 'https://coin98.s3.ap-southeast-1.amazonaws.com/sui.jpg',
  ETHW: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/etherPoW.png',
  SEI: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/sei.png',
  INJ: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/injective.png',
  EVMOS: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/evmos.png',
  JUNO: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/juno.png',
  KUJI: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/kuji.png',
  OSMO: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/osmo.png',
  STARS: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/stars.png',
  STRD: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/stride.png',
  ROSE: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/oasis.png',
  UMEE: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/umee.png',
  BLD: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/agoric.png',
  CONST: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/archway.png'
}

export const ALGO = {
  hd: 'hd',
  nacl: 'nacl',
  polkadot: 'polkadot'
}

export const STANDARD_KEY = {
  old: 'old',
  mid: 'mid',
  new: 'new'
}

export const CHAIN_ID = {
  sei: 'sei',
  functionXEVM: 'functionXEVM',
  zkSyncEra: 'zkSyncEra',
  zkSyncPolygon: 'zkSyncPolygon',
  baseTest: 'baseTest',
  terra2: 'terra2',
  evm: 'evm',

  secretNetwork: 'secretNetwork',
  elrond: 'elrond',
  conflux: 'conflux',
  tezos: 'tezos',
  harmony: 'harmony',
  aurora: 'aurora',
  // 11.2.0
  kucoin: 'kucoin',
  boba: 'boba',
  arbitrum: 'arbitrum',
  arbitrumXdai: 'arbitrumXdai',
  optimism: 'optimism',

  ETH: 'ether',
  BSC: 'binanceSmart',
  TRX: 'tron',

  kava: 'kava',
  link: 'link',
  avax: 'avax',
  avaxX: 'avaxX',
  near: 'near',
  binanceSmart: 'binanceSmart',
  fantom: 'fantom',
  matic: 'matic',

  customCreate: 'customCreate',
  custom: 'custom',
  multiChain: 'multiChain',
  hardwareWallet: 'hardwareWallet',
  bitcoin: 'bitcoin',
  tomo: 'tomo',
  binance: 'binance',
  ether: 'ether',
  etherPoW: 'etherPoW',
  eos: 'eos',
  band: 'band',
  solana: 'solana',
  tron: 'tron',
  polkadot: 'polkadot',
  celo: 'celo',
  cosmos: 'cosmos',
  heco: 'heco',
  kusama: 'kusama',
  doge: 'doge',

  thor: 'thor',
  terra: 'terra',
  persistence: 'persistence',

  xDai: 'xDai',
  kardia: 'kardia',
  ronin: 'ronin',
  okex: 'okex',
  klaytn: 'klaytn',
  gate: 'gate',

  // 17/5/2022
  // starknet: 'starknet', L2
  // zksync: 'zksync', L2
  cronos: 'cronos',
  bittorrent: 'bittorrent',
  ton: 'ton',
  theta: 'theta', //
  thetaFuel: 'thetaFuel',
  platon: 'platon', //
  moonbeam: 'moonbeam', //
  algorand: 'algorand',
  functionX: 'functionX',
  casper: 'casper',

  // Enable Production Only
  sui: 'suiMainnet',
  aptosLabs: 'aptosLabs',
  aptos: 'aptos',
  aptosDev: 'aptosDev',
  seiMainnet: 'sei',
  archwayMainnet: 'archwayMainnet',
  injective: 'injective',
  osmosis: 'osmosis',
  evmos: 'evmos',
  juno: 'juno',
  agoric: 'agoric',
  archway: 'archway',
  kaneda: 'kaneda',
  oasis: 'oasis',
  kujira: 'kujira',
  stargaze: 'stargaze',
  umee: 'umee',
  stride: 'stride',
  aura: 'aura',
  xrp: 'xrp',
  bitcoinTestNet: 'bitcoinTestNet',
  xion: 'xion'
}

export const CHAIN_DATA: any = {
  multiChain: {
    isOther: true,
    isMnemonic: true,
    name: 'Multi-Chain',
    image: 'app_multi_chain',
    chain: CHAIN_ID.multiChain,
    trcName: 'All Blockchains'
  },
  evm: {
    isOther: true,
    name: 'EVM Wallet',
    image: 'app_evm',
    chain: CHAIN_ID.evm,
    trcName: 'EVM Wallet'
  },
  hardwareWallet: {
    isOther: true,
    isHardware: true,
    name: 'Hardware Wallet',
    image: 'app_ledger',
    chain: CHAIN_ID.hardwareWallet,
    trcName: 'Import hardware wallet'
  },
  customCreate: {
    isOther: true,
    name: 'Custom Network',
    image: 'app_custom_network',
    chain: CHAIN_ID.customCreate,
    trcName: 'Create Custom Network'
  },
  custom: {
    isOther: true,
    name: 'Custom Network',
    image: 'app_box',
    chain: CHAIN_ID.custom,
    trcName: 'Custom Network'
  },
  binanceSmartTest: {
    isOther: true,
    numChainId: 97,
    chainId: '0x61',
    rpcURL: 'https://data-seed-prebsc-1-s1.binance.org:8545'
  },

  bitcoin: {
    path: "m/84'/0'/0'/0/0",
    oldNumPath: 0,
    subName: 'BTC',
    algo: ALGO.hd,
    numPath: 0,
    numLoad: 5,
    isFee: true,
    isMnemonic: true,
    image: 'app_bitcoin',
    id: 'bitcoin',
    name: 'Bitcoin',
    shortName: 'Bitcoin',
    imageLink: COIN_IMAGE.BTC,
    symbol: 'BTC',
    chain: CHAIN_ID.bitcoin,
    trcName: 'BTC',
    scan: 'https://www.blockchain.com/btc'
  },
  ether: {
    subName: 'ETH',
    isCrawlNFTServices: true,
    isCrawlServices: true,
    numChainId: 1,
    chainId: '0x1',
    numLoad: 0,
    isSupportedEIP1559: true,
    isToken: true,
    isBridge: true,
    isSupportedNFT: true,

    trcToken: 'ERC20',
    nftToken: 'ERC721',
    wrapped: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
    balances: '0x38bb7b9b87bdfbed883aaf50a2f411d330fe32d6',
    multisend: '0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6',
    stake: '0x836bf46520C373Fdc4dc7E5A3bAe735d13bD44e3',
    isSupportedV2: true,
    isWeb3: true,
    isFee: true,
    image: 'app_ethereum',
    id: 'ethereum',
    name: 'Ethereum',
    shortName: 'Ethereum',
    imageLink: COIN_IMAGE.ETH,
    symbol: 'ETH',
    chain: CHAIN_ID.ether,
    trcName: 'ETH ERC20 ERC721',
    rpcURL: 'https://mainnet.infura.io/v3/92d53cee52834368b0fabb42fa1b5570',
    scan: 'https://etherscan.io'
  },
  etherPoW: {
    numChainId: 10001,
    chainId: '0x2711',
    numLoad: 0,
    isSupportedEIP1559: true,
    isToken: true,
    isBridge: true,
    isSupportedNFT: true,

    trcToken: 'ERC20W',
    nftToken: 'ERC721W',
    balances: '0x38bb7b9b87bdfbed883aaf50a2f411d330fe32d6',
    multisend: '0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6',
    stake: '0x836bf46520C373Fdc4dc7E5A3bAe735d13bD44e3',
    isSupportedV2: true,
    isWeb3: true,
    isFee: true,
    image: 'app_ethereum_pow',
    id: 'ethereum-pow-iou',
    name: 'Ethereum PoW',
    shortName: 'ETHPoW',
    imageLink: COIN_IMAGE.ETHW,
    symbol: 'ETHW',
    chain: CHAIN_ID.etherPoW,
    trcName: 'ETHW ERC20W ERC721W',
    rpcURL: 'https://mainnet.ethereumpow.org',
    scan: 'https://www.oklink.com/en/ethw'
  },
  binanceSmart: {
    isCrawlNFTServices: true,
    isCrawlServices: true,
    numChainId: 56,
    chainId: '0x38',
    numLoad: 1,
    isBridge: true,
    isToken: true,
    isSupportedNFT: true,
    nftToken: 'BEP721',
    trcToken: 'BEP20',
    symbolSpecial: 'BSC',
    wrapped: '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56',
    balances: '0xA6762c710852681c4593C10c4304C5211FB2122c',
    multisend: '0x2E1D30460265bFEBedacf5bb6f9A80F0E74B7498',
    nftMint: '0xc4cAd0938256ABA4417c565044Be2c2EB77096cb',
    stake: '0x08ac9c38ce078b9b81e5ab5bf8aafc3d2db94385',
    subName: 'BSC',

    isSupportedV2: true,
    isWeb3: true,
    isFee: true,
    image: 'app_binance',

    id: 'binancecoin',
    name: 'BNB Smart Chain',
    shortName: 'BSC',
    imageLink: COIN_IMAGE.BNB,
    symbol: 'BNB',
    chain: CHAIN_ID.binanceSmart,
    trcName: 'BNB BEP20',
    rpcURL: 'https://bscrpc.com',
    scan: 'https://bscscan.com'
  },
  heco: {
    decimals: 18,
    numChainId: 128,
    chainId: '0x80',
    numLoad: 1,
    isToken: true,
    isSupportedEIP1559: false,
    isSupportedNFT: true,
    trcToken: 'HRC20',
    nftToken: 'HRC721',
    isWeb3: true,
    isFee: true,
    image: 'app_heco',
    wrapped: '0x0298c2b32eaE4da002a15f36fdf7615BEa3DA047',
    balances: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    multisend: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    nftMint: '0x67807b9f5B9757C0c79347F0b3f360C15c5E6aFF',

    id: 'huobi-token',
    name: 'HECO Chain',
    shortName: 'Huobi',
    imageLink: COIN_IMAGE.HT,
    symbol: 'HT',
    chain: CHAIN_ID.heco,
    trcName: 'HT HRC20',
    rpcURL: 'https://http-mainnet.hecochain.com',
    scan: 'https://hecoinfo.com'
  },
  okex: {
    numChainId: 66,
    chainId: '0x42',
    numLoad: 2,
    isSupportedNFT: true,
    balances: '0x5c93f4b35d3dd97ef481881aa33d00f76806fdad',
    multisend: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    nftMint: '0xAE12C5930881c53715B369ceC7606B70d8EB229f',
    isToken: true,
    id: 'oec-token',
    name: 'OKXChain',
    image: 'app_okex',
    symbol: 'OKT',
    chain: CHAIN_ID.okex,
    imageLink: COIN_IMAGE.OKT,
    icon: 'okex',
    trcToken: 'KIP20',
    nftToken: 'NFT',
    trcName: 'OKT KIP10 KIP20 NFT',
    isFee: true,
    isWeb3: true,
    rpcURL: 'https://exchainrpc.okex.org',
    scan: 'https://www.oklink.com/okexchain'
  },
  terra2: {
    prefix: 'terra',
    numPath: 330,

    numLoad: 3,
    isToken: true,
    trcToken: 'CW20',

    isCosmos: true,
    isMemo: true,

    id: 'terra-luna-2',
    name: 'Terra 2.0',
    image: 'app_terra2',
    symbol: 'LUNA',
    denom: 'uluna',
    imageLink: COIN_IMAGE.LUNA2,
    chain: CHAIN_ID.terra2,
    trcName: 'LUNA CW20',
    scan: 'https://finder.terra.money/mainnet/',
    chainId: 'phoenix-1'
  },
  gate: {
    numChainId: 86,
    chainId: '0x56',
    numLoad: 2,
    balances: '0x5c93f4b35d3dd97ef481881aa33d00f76806fdad',
    multisend: '0x963e1bcd1f82724bd8fa16a3b6962d100fb287fc',
    nftMint: '0x67807b9f5B9757C0c79347F0b3f360C15c5E6aFF',
    isSupportedNFT: true,
    isToken: true,
    id: 'gatechain-token',
    name: 'GateChain',
    image: 'app_gate',
    symbol: 'GT',
    chain: CHAIN_ID.gate,
    imageLink: COIN_IMAGE.GT,
    icon: 'gate',
    trcToken: 'GRC20',
    nftToken: 'GRC721',
    trcName: 'GT GRC20 GRC721',
    isFee: true,
    isWeb3: true,
    rpcURL: 'https://evm.gatenode.cc',
    scan: 'https://gatescan.org'
  },

  kucoin: {
    numChainId: 321,
    chainId: '0x141',

    numLoad: 2,
    isToken: true,
    subName: 'KCS',
    trcToken: 'KRC20',
    nftToken: 'KRC721',
    balances: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    multisend: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    nftMint: '0xAE12C5930881c53715B369ceC7606B70d8EB229f',
    isWeb3: true,
    isSupportedNFT: true,
    isFee: true,
    image: 'app_kucoin',
    id: 'kucoin-shares',
    name: 'KuCoin Community Chain',
    shortName: 'Kucoin',
    imageLink: COIN_IMAGE.KCS,
    symbol: 'KCS',
    chain: CHAIN_ID.kucoin,
    trcName: 'KCS KRC20 KRC721',
    rpcURL: 'https://rpc-mainnet.kcc.network',
    scan: 'https://explorer.kcc.io/en'
  },
  solana: {
    isCrawlNFTServices: true,
    path: "m/44'/501'/0'/0'",
    gasDefault: 0.000005,
    decimals: 9,
    isSolana: true,
    numPath: 501,
    numLoad: 1,
    isToken: true,
    trcToken: 'SPL',
    nftToken: 'SPL NFT',
    multisend: true,
    isBridge: true,
    isSupportedNFT: true,

    image: 'app_solana',

    id: 'solana',
    name: 'Solana',
    shortName: 'Solana',
    imageLink: COIN_IMAGE.SOL,
    symbol: 'SOL',
    chain: CHAIN_ID.solana,
    trcName: 'SOL SPL',
    rpcURL: 'https://information.coin98.com/solanaV4',
    scan: 'https://solscan.io'
  },
  near: {
    path: "m/44'/397'/0'",
    numPath: 397,
    numLoad: 2,
    isToken: true,
    trcToken: 'NEP141',

    image: 'app_near',
    id: 'near',
    name: 'Near',
    imageLink: COIN_IMAGE.NEAR,
    symbol: 'NEAR',
    trcName: 'NEAR NEP141',
    chain: CHAIN_ID.near,
    scan: 'https://explorer.near.org',
    rpcURL: 'https://public-rpc.blockpi.io/http/near',
    // rpcURL: 'https://rpc.mainnet.near.org',
    scanTxs: 'transactions',
    scanAddr: 'accounts'
  },
  avax: {
    isCrawlNFTServices: true,
    isCrawlServices: true,
    isSupportedEIP1559: true,
    oldNumPath: 9000,

    isBridge: true,
    numChainId: 43114,
    chainId: '0xa86a',

    numLoad: 1,
    isSupportedNFT: true,
    isToken: true,
    trcToken: 'ARC20',
    nftToken: 'ARC721',
    symbolSpecial: 'CCHAIN',
    wrapped: '0xc7198437980c041c805A1EDcbA50c1Ce5db95118',
    balances: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    multisend: '0xAE12C5930881c53715B369ceC7606B70d8EB229f',
    nftMint: '0x0eCE57A677D5e72D1ad45774239e23463CF1d743',

    subName: 'C',

    isSupportedV2: true,
    isWeb3: true,
    isFee: true,
    image: 'app_avalancher',
    id: 'avalanche-2',
    name: 'Avalanche C-Chain',
    shortName: 'Avalanche',
    imageLink: COIN_IMAGE.AVAX,
    symbol: 'AVAX',
    chain: CHAIN_ID.avax,
    trcName: 'AVAX-C ARC20',
    rpcURL: 'https://api.avax.network/ext/bc/C/rpc',
    scan: 'https://snowtrace.io'
  },
  avaxX: {
    path: "m/44'/9000'/0'/0/0",
    algo: ALGO.hd,
    numPath: 9000,
    numLoad: 5,
    isBridge: true,
    symbolSpecial: 'XCHAIN',
    subName: 'X',
    image: 'app_avalancher',
    id: 'avalanche-2',
    name: 'Avalanche X-Chain',
    shortName: 'Avalanche',
    imageLink: COIN_IMAGE.AVAX,
    symbol: 'AVAX',
    chain: CHAIN_ID.avaxX,
    trcName: 'AVAX-X',
    scan: 'https://avascan.info/blockchain/x'
  },
  tron: {
    algo: ALGO.hd,
    path: "m/44'/60'/0'/0/0",
    decimals: 6,
    isLibrary: true,
    numLoad: 1,
    isToken: true,
    isBridge: true,
    trcToken: 'TRC20',
    trcSubName: 'TRC10',

    image: 'app_tron',

    id: 'tron',
    name: 'Tron',
    shortName: 'Tron',
    imageLink: COIN_IMAGE.TRX,
    symbol: 'TRX',
    chain: CHAIN_ID.tron,
    trcName: 'TRX TRC10 TRC20',
    scan: 'https://tronscan.org/#',
    scanTxs: 'transaction'
  },
  matic: {
    isCrawlNFTServices: true,
    isCrawlServices: true,
    // isSupportedEIP1559: true,
    numChainId: 137,
    chainId: '0x89',
    numLoad: 2,
    isToken: true,
    trcToken: 'PRC20',
    nftToken: 'PRC721',
    isSupportedV2: true,
    isSupportedNFT: true,
    isFee: true,
    isWeb3: true,
    wrapped: '0xc2132D05D31c914a87C6611C10748AEb04B58e8F',
    balances: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    multisend: '0x67807b9f5B9757C0c79347F0b3f360C15c5E6aFF',
    nftMint: '0x9aE5c1cf82aF51CBB83D9A7B1C52aF4B48E0Bb5E',

    id: 'matic-network',
    name: 'Polygon',
    image: 'app_polygon',
    imageLink: COIN_IMAGE.MATIC,
    symbol: 'MATIC',
    chain: CHAIN_ID.matic,
    trcName: 'MATIC PRC20',
    rpcURL: 'https://rpc-mainnet.maticvigil.com',
    scan: 'https://polygonscan.com'
  },
  fantom: {
    isCrawlNFTServices: true,
    isCrawlServices: true,
    numChainId: 250,
    chainId: '0xFA',

    numLoad: 2,
    isSupportedV2: true,
    isToken: true,
    isSupportedNFT: true,
    trcToken: 'FRC20',
    nftToken: 'FRC721',
    wrapped: '0x04068DA6C83AFCFA0e13ba15A6696662335D5B75',
    balances: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    multisend: '0x5c93f4b35d3dd97ef481881aa33d00f76806fdad',
    nftMint: '0x67807b9f5B9757C0c79347F0b3f360C15c5E6aFF',

    isFee: true,
    isWeb3: true,

    id: 'fantom',
    name: 'Fantom',
    image: 'app_fantom',
    imageLink: COIN_IMAGE.FTM,
    symbol: 'FTM',
    chain: CHAIN_ID.fantom,
    trcName: 'FANTOM FRC20',
    rpcURL: 'https://rpcapi.fantom.network',
    scan: 'https://ftmscan.com'
  },
  xDai: {
    isSupportedEIP1559: true,
    numChainId: 100,
    chainId: '0x64',

    numLoad: 2,
    balances: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multisend: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    nftMint: '0xAE12C5930881c53715B369ceC7606B70d8EB229f',
    isSupportedNFT: true,
    isToken: true,
    id: 'xdai',
    name: 'Gnosis Chain',
    image: 'app_xDai',
    symbol: 'XDAI',
    chain: CHAIN_ID.xDai,
    imageLink: COIN_IMAGE.XDAI,
    icon: 'xDai',
    trcToken: 'XRC20',
    nftToken: 'XRC721',
    trcName: 'XDAI XRC20',
    isFee: true,
    isWeb3: true,
    rpcURL: 'https://rpc.gnosischain.com',
    scan: 'https://blockscout.com/xdai/mainnet'
  },
  polkadot: {
    SS58: 0,
    algo: ALGO.polkadot,
    isPolkadot: true,
    numLoad: 3,
    image: 'app_polkadot',

    isMnemonic: true,
    id: 'polkadot',
    name: 'Polkadot',
    shortName: 'Polkadot',
    imageLink: COIN_IMAGE.DOT,
    symbol: 'DOT',
    chain: CHAIN_ID.polkadot,
    trcName: 'DOT',
    rpcURL: 'rpc.polkadot.io',
    scan: 'https://polkadot.subscan.io',
    scanTxs: 'extrinsic',
    scanAddr: 'account'
  },
  kusama: {
    SS58: 2,
    algo: ALGO.polkadot,
    isPolkadot: true,
    numLoad: 3,
    image: 'app_kusama',

    isMnemonic: true,
    id: 'kusama',
    name: 'Kusama',
    shortName: 'Kusama',
    imageLink: COIN_IMAGE.KSM,
    symbol: 'KSM',
    chain: CHAIN_ID.kusama,
    trcName: 'KSM',
    rpcURL: 'kusama-rpc.polkadot.io',
    scan: 'https://kusama.subscan.io'
  },
  cosmos: {
    prefix: 'cosmos',
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isMemo: true,
    isFactory: true,

    chainId: 'cosmoshub-4',
    id: 'cosmos',
    name: 'Cosmos',
    image: 'app_cosmos',
    symbol: 'ATOM',
    imageLink: COIN_IMAGE.ATOM,
    chain: CHAIN_ID.cosmos,
    trcName: 'ATOM',
    scan: 'https://www.mintscan.io/cosmos',
    scanTxs: 'txs',
    scanAddr: 'account',
    scanBlocks: 'blocks/id'
  },
  thor: {
    prefix: 'thor',
    numPath: 931,

    numLoad: 3,
    isCosmos: true,
    isMemo: true,
    id: 'thorchain',
    name: 'THORChain',
    image: 'app_thorchain',
    imageLink: COIN_IMAGE.RUNE,
    symbol: 'RUNE',
    chain: CHAIN_ID.thor,
    trcName: 'RUNE',
    scan: 'https://viewblock.io/thorchain'
  },
  aura: {
    prefix: 'aura',
    numPath: 118,
    nftToken: 'CW721',

    numLoad: 1,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: true,
    isSupportedNFT: true,
    isDynamic: true,

    chainId: 'aura',
    id: 'aura-network',
    name: 'Aura Xstaxy Mainnet',
    image: 'app_aura_network',
    symbol: 'AURA',
    imageLink: 'COIN_IMAGE.AURA',
    chain: CHAIN_ID.aura,
    trcName: 'AURA CW-20 CW-721',
    scan: 'https://aurascan.io',
    rpcURL: 'https://rpc.aura.network',
    restURL: 'https://lcd.aura.network',
    scanTxs: 'transaction',
    scanAddr: 'account'
  },
  terra: {
    prefix: 'terra',
    numPath: 330,

    numLoad: 3,
    isToken: true,
    trcToken: 'CW20',

    isCosmos: true,
    isMemo: true,

    id: 'terra-luna',
    name: 'Old Terra',
    image: 'app_terra',
    symbol: 'LUNC',
    denom: 'uluna',
    imageLink: COIN_IMAGE.LUNA,
    chain: CHAIN_ID.terra,
    trcName: 'LUNC CW20',
    scan: 'https://finder.terra.money/columbus-5',
    chainId: 'columbus-5'
  },
  band: {
    prefix: 'band',
    numPath: 494,

    numLoad: 3,
    isCosmos: true,
    isMemo: true,
    id: 'band-protocol',
    name: 'BandChain',
    image: 'app_band',
    imageLink: COIN_IMAGE.BAND,
    symbol: 'BAND',
    trcName: 'BAND',
    chain: CHAIN_ID.band,
    scan: 'https://cosmoscan.io',
    scanAddr: 'account'
  },
  kava: {
    prefix: 'kava',
    numPath: 459,

    numLoad: 3,
    isCosmos: true,
    isMemo: true,
    isFactory: true,

    id: 'kava',
    name: 'Kava',
    image: 'app_kava',
    imageLink: COIN_IMAGE.KAVA,
    symbol: 'KAVA',
    chain: CHAIN_ID.kava,
    trcName: 'KAVA',
    scan: 'https://www.mintscan.io/kava',
    scanTxs: 'txs',
    scanAddr: 'account',
    scanBlocks: 'blocks/id'
  },
  secretNetwork: {
    prefix: 'secret',
    numPath: 529,

    numLoad: 3,
    isCosmos: true,
    isMemo: true,
    isFactory: true,

    chainId: 'secret-4',
    id: 'secret',
    name: 'Secret Network',
    image: 'app_secret_network',
    imageLink: COIN_IMAGE.SCRT,
    symbol: 'SCRT',
    chain: CHAIN_ID.secretNetwork,
    trcName: 'SCRT',
    scan: 'https://secretnodes.com/secret/chains/secret-4',
    scanTxs: 'transactions',
    scanAddr: 'account',
    scanBlocks: 'blocks/id'
  },
  persistence: {
    prefix: 'persistence',
    numPath: 750,

    numLoad: 3,
    isCosmos: true,
    isMemo: true,
    isFactory: true,

    chainId: 'core-1',
    id: 'persistence',
    name: 'Persistence',
    image: 'app_-persistence',
    imageLink: COIN_IMAGE.XPRT,
    symbol: 'XPRT',
    chain: CHAIN_ID.persistence,
    trcName: 'XPRT',
    scan: 'https://explorer.persistence.one',
    scanBlocks: 'blocks',
    scanTxs: 'transactions',
    scanAddr: 'wallet'
  },

  binance: {
    prefix: 'bnb',
    numPath: 714,

    numLoad: 2,
    isToken: true,
    trcToken: 'BEP2',
    symbolSpecial: 'BC',

    isCosmos: true,
    isMemo: true,
    subName: 'BC',

    image: 'app_binance',

    id: 'binancecoin',
    name: 'BNB Beacon Chain',
    shortName: 'Binance',
    imageLink: COIN_IMAGE.BNB,
    symbol: 'BNB',
    chain: CHAIN_ID.binance,
    trcName: 'BNB BEP2 BEP8',
    scan: 'https://explorer.binance.org'
  },
  functionX: {
    prefix: 'fx',
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,

    chainId: 'fxcore',
    id: 'fx-coin',
    name: 'Function X',
    image: 'app_functionX',
    symbol: 'FX',
    imageLink: COIN_IMAGE.FX,
    chain: CHAIN_ID.functionX,
    trcName: 'FX FXRC20',
    scan: 'https://explorer.functionx.io/fxcore',
    rpcURL: 'https://fx-json.functionx.io:26657',
    scanTxs: 'tx',
    scanAddr: 'address'
  },
  functionXEVM: {
    prefix: 'fx',
    decimals: 18,
    numChainId: 530,
    chainId: '0x212',
    numLoad: 1,
    isWeb3: true,
    id: 'fx-coin',
    name: 'Function X',
    image: 'app_functionX',
    symbol: 'FX',
    imageLink: COIN_IMAGE.FX,
    chain: CHAIN_ID.functionX,
    trcName: 'FX FXRC20',
    scan: 'https://starscan.io/evm',
    rpcURL: 'https://fx-json-web3.functionx.io:8545',
    scanTxs: 'tx',
    scanAddr: 'address'
  },
  elrond: {
    path: "m/44'/508'/0'/0'",
    prefix: 'erd',
    numPath: 508,
    nftToken: 'SFT',
    numLoad: 3,
    feeDefault: 0.00005,
    isToken: true,
    trcToken: 'ESDT',

    id: 'elrond-erd-2',
    name: 'Elrond',
    image: 'app_elrond',
    imageLink: COIN_IMAGE.EGLD,
    symbol: 'EGLD',
    chain: CHAIN_ID.elrond,
    trcName: 'EGLD ESDT SFT',
    scan: 'https://explorer.elrond.com',
    scanTxs: 'transactions',
    scanAddr: 'accounts',
    scanBlocks: 'blocks'
  },
  tezos: {
    feeDefault: 0.0015,
    prefix: 'tz1',
    nftToken: 'FA2',
    isToken: true,
    trcToken: 'FA1.2',
    numLoad: 2,

    id: 'tezos',
    name: 'Tezos',
    image: 'app_tezos',
    imageLink: COIN_IMAGE.XTZ,
    symbol: 'XTZ',
    rpcURL: 'https://nd-980-936-622.p2pify.com/e6ea03e1d3a5bcc4297e43c13622a905',
    chain: CHAIN_ID.tezos,
    trcName: 'XTZ FA1.2 FA2',
    scan: 'https://tezblock.io',
    scanTxs: 'transaction',
    scanAddr: 'account',
    scanBlocks: 'block'
  },
  celo: {
    // mainAddress: '0x471ece3750da237f93b8e339c536989b8978a438',
    oldNumPath: 52752,

    numChainId: 42220,
    chainId: '0xA4EC',

    numLoad: 1,
    isSupportedNFT: true,
    isFee: true,
    isToken: true,
    balances: '0x5c93f4b35d3dd97ef481881aa33d00f76806fdad',
    multisend: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    nftMint: '0xAE12C5930881c53715B369ceC7606B70d8EB229f',
    isWeb3: true,
    nftToken: 'CELO721',
    image: 'app_celo',
    id: 'celo',
    name: 'Celo',
    shortName: 'Celo',
    imageLink: COIN_IMAGE.CELO,
    symbol: 'CELO',
    chain: CHAIN_ID.celo,
    trcName: 'CELO CUSD',
    rpcURL: 'https://forno.celo.org',
    scan: 'https://explorer.celo.org'
  },
  tomo: {
    oldNumPath: 889,

    numChainId: 88,
    chainId: '0x58',
    // numChainId: 4,
    // chainId: '0x4',

    numLoad: 2,
    isBridge: true,
    isToken: true,
    isSupportedNFT: true,
    trcToken: 'TRC21',
    nftToken: 'TRC721',
    isWeb3: true,
    isFee: true,
    image: 'app_tomochain',
    balances: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    // multisend: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    nftMint: '0xAE12C5930881c53715B369ceC7606B70d8EB229f',

    id: 'tomochain',
    name: 'TomoChain',
    shortName: 'Tomo',
    imageLink: COIN_IMAGE.TOMO,
    symbol: 'TOMO',
    chain: CHAIN_ID.tomo,
    trcName: 'TOMO TRC21',
    rpcURL: 'https://rpc.tomochain.com',
    scan: 'https://scan.tomochain.com'
  },
  algorand: {
    path: "m/44'/501'/0'/0'",
    numPath: 501,
    feeDefault: 0.001,

    trcToken: 'ALGO',
    nftToken: 'ALGO721',
    isToken: true,
    id: 'algorand',
    name: 'Algorand',
    image: 'app_algorand',
    imageLink: COIN_IMAGE.ALGO,
    symbol: 'ALGO',
    chain: CHAIN_ID.algorand,
    trcName: 'ALGO ALGO721',
    scan: 'https://algoexplorer.io'
  },
  casper: {
    path: "m/44'/501'/0'/0'",
    numPath: 501,
    trcToken: 'CSPR',
    nftToken: 'CSPR-NFT',
    id: 'casper-network',
    name: 'Casper',
    image: 'app_casper',
    isMemo: true,
    imageLink: COIN_IMAGE.CSPR,
    symbol: 'CSPR',
    chain: CHAIN_ID.casper,
    trcName: 'CSPR',
    scanTxs: 'deploy',
    scanAddr: 'account',
    scan: 'https://cspr.live'
  },
  kardia: {
    numChainId: 24,
    chainId: '0x18',

    numLoad: 2,
    isToken: true,
    id: 'kardiachain',
    name: 'KardiaChain',
    image: 'app_kardia',
    symbol: 'KAI',
    chain: CHAIN_ID.kardia,
    imageLink: COIN_IMAGE.KAI,
    icon: 'kardia',
    subName: 'KAI',
    trcToken: 'KRC20',
    nftToken: 'KRC721',
    trcName: 'KAI KRC20 KRC721',
    balances: '0x8ef3C4Bf105Ec17cbeD7615C5711d2F4D44a4194',
    multisend: '0xf21201135568A81c9046d60a003eC2B883173F2f',
    nftMint: '0x8347CD0aaF874259e9d577BeE08231F648C3fc29',

    isFee: true,
    isWeb3: true,
    rpcURL: 'https://rpc.kardiachain.io',
    scan: 'https://explorer.kardiachain.io'
  },
  ronin: {
    prefix: 'ronin:',
    numChainId: 2020,
    chainId: '0x7e4',

    numLoad: 2,
    isToken: true,
    isSupportedNFT: true,
    id: 'ronin',
    name: 'Ronin',
    image: 'app_ronin',
    nftToken: 'RRC721',
    symbol: 'RON',
    chain: CHAIN_ID.ronin,
    imageLink: COIN_IMAGE.RON,
    icon: 'ronin',
    trcToken: 'RRC20',
    trcName: 'RON RRC20 RRC721',
    isFee: true,
    isWeb3: true,
    rpcURL: 'https://api.roninchain.com/rpc',
    scan: 'https://explorer.roninchain.com'
  },

  klaytn: {
    numChainId: 8217,
    chainId: '0x2019',

    numLoad: 2,
    balances: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multisend: '0x5c93f4b35d3dd97ef481881aa33d00f76806fdad',

    isSupportedNFT: true,
    isToken: true,
    id: 'klay-token',
    name: 'Klaytn',
    image: 'app_klaytn',
    symbol: 'KLAY',
    trcToken: 'KIP7',
    nftToken: 'KIP37',

    chain: CHAIN_ID.klaytn,
    imageLink: COIN_IMAGE.KLAY,
    icon: 'klaytn',
    trcName: 'KLAY KIP7 KIP37',
    isFee: true,
    isWeb3: true,
    scan: 'https://scope.klaytn.com',
    rpcURL: 'https://kaikas.cypress.klaytn.net:8651',
    scanAddr: 'account'
  },
  harmony: {
    prefix: 'one',
    numChainId: 1666600000,
    chainId: '0x63564C40',
    numLoad: 1,
    isToken: true,
    isSupportedNFT: true,
    nftToken: 'HRC721',
    trcToken: 'HRC20',
    balances: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multisend: '0x9aE5c1cf82aF51CBB83D9A7B1C52aF4B48E0Bb5E',
    nftMint: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',

    isWeb3: true,
    isFee: true,
    image: 'app_harmony',

    id: 'harmony',
    name: 'Harmony',
    imageLink: COIN_IMAGE.ONE,
    symbol: 'ONE',
    chain: CHAIN_ID.harmony,
    trcName: 'ONE HRC20 HRC721',
    rpcURL: 'https://api.harmony.one',
    scan: 'https://explorer.harmony.one'
  },
  conflux: {
    path: "m/44'/60'/0'/0/0",
    algo: ALGO.hd,
    numPath: 60,
    feeDefault: 0.00005,

    prefix: 'cfx',
    trcToken: 'CRC20',
    nftToken: 'CRC721',
    isToken: true,
    numLoad: 2,

    id: 'conflux-token',
    name: 'Conflux',
    image: 'app_conflux',
    imageLink: COIN_IMAGE.CFX,
    symbol: 'CFX',
    chain: CHAIN_ID.conflux,
    trcName: 'CFX CRC20 CRC721',
    scan: 'https://www.confluxscan.io',
    scanTxs: 'transaction',
    scanAddr: 'address',
    scanBlocks: 'block'
  },
  optimism: {
    isCrawlNFTServices: true,
    // defaultGas: 882000,
    // mainAddress: '0x4200000000000000000000000000000000000006',
    isL2: true,
    isBridge: true,
    numChainId: 10,
    chainId: '0xA',
    // numChainId: 69,
    // chainId: '0x45',

    numLoad: 2,
    isToken: true,
    trcToken: 'ERC20 OPT',
    nftToken: 'ERC721 OPT',
    // balances: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    // multisend: '0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6',
    isWeb3: true,
    isFee: true,
    image: 'app_optimism',
    id: 'ethereum',
    name: 'Optimism',
    shortName: 'Optimism',
    imageLink: COIN_IMAGE.OP,
    symbol: 'ETH',
    symbolSpecial: 'OP',
    chain: CHAIN_ID.optimism,
    trcName: 'ETH ERC20 ERC721',
    rpcURL: 'https://mainnet.optimism.io',
    // rpcURL: 'https://kovan.optimism.io',
    scan: 'https://optimistic.etherscan.io'
  },
  boba: {
    // defaultGas: 80000000,
    // mainAddress: '0x4200000000000000000000000000000000000006',
    isL2: true,
    isBridge: true,
    numChainId: 288,
    chainId: '0x120',
    // numChainId: 28,
    // chainId: '0x1C',

    numLoad: 2,
    isToken: true,
    trcToken: 'ERC20 BOBA',
    nftToken: 'ERC721 BOBA',
    // multisend: '0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6',
    isWeb3: true,
    isFee: true,
    image: 'app_boba',
    id: 'ethereum',
    name: 'Boba Network',
    shortName: 'Boba Network',
    imageLink: COIN_IMAGE.BOBA,
    symbol: 'ETH',
    symbolSpecial: 'BOBA',
    chain: CHAIN_ID.boba,
    trcName: 'ETH ERC20 ERC721',
    rpcURL: 'https://mainnet.boba.network',
    scan: 'https://blockexplorer.boba.network'
  },
  zkSyncPolygon: {
    numChainId: 1101,
    chainId: '0x44D',
    numLoad: 0,
    isToken: true,
    isSupportedNFT: true,

    trcToken: 'ERC20',
    nftToken: 'ERC721',
    balances: '0x8bfcbf5cbb6729c11ccb2949C149D8928b6C932C',
    multisend: '0xafb9013228D365AcEE408543B284240F7965EDDD',
    nftMint: '0x8437BF9557eE3a32e964a8Ff300DF69379d747a4',
    isWeb3: true,
    isFee: true,
    image: 'zkSyncPolygon',
    id: 'ethereum',
    name: 'Polygon zkEVM',
    shortName: 'Polygon zkEVM',
    symbolSpecial: 'zkPolygon',
    imageLink: COIN_IMAGE.ETH,
    symbol: 'ETH',
    chain: CHAIN_ID.zkSyncPolygon,
    trcName: 'ETH ERC20 ERC721',
    rpcURL: 'https://zkevm-rpc.com',
    scan: 'https://zkevm.polygonscan.com'
  },
  zkSyncEra: {
    symbolSpecial: 'zkEra',
    numChainId: 324,
    chainId: '0x144',
    numLoad: 0,
    isToken: true,
    isSupportedNFT: true,
    trcToken: 'ERC20',
    nftToken: 'ERC721',
    balances: '0xeAe3Fc95365C0F3258506c867E172f72450D69d7',
    multisend: '0xf518a374433Ea889d25f942A799F717D10Fd4A44',
    nftMint: '0x244f7dF740Cd37c5DBa635D52BF01146ACb56c28',
    isWeb3: true,
    isFee: true,
    image: 'zkSyncEra',
    id: 'ethereum',
    name: 'zkSync Era',
    shortName: 'zkSync Era',
    imageLink: COIN_IMAGE.ETH,
    symbol: 'ETH',
    chain: CHAIN_ID.zkSyncEra,
    trcName: 'ETH ERC20 ERC721',
    rpcURL: 'https://mainnet.era.zksync.io',
    scan: 'https://explorer.zksync.io'
  },
  arbitrum: {
    isCrawlServices: true,
    isCrawlNFTServices: true,
    // defaultGas: 7000000,
    isL2: true,
    isBridge: true,
    numChainId: 42161,
    chainId: '0xA4B1',
    // numChainId: 421611,
    // chainId: '0x66EEB',
    isSupportedNFT: true,
    numLoad: 2,
    isToken: true,
    trcToken: 'ERC20 ARB',
    nftToken: 'ERC721 ARB',
    // balances: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multisend: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    isWeb3: true,
    isFee: true,
    image: 'app_arbitrum',
    id: 'ethereum',
    name: 'Arbitrum',
    shortName: 'Arbitrum',
    imageLink: COIN_IMAGE.ETHARB,
    symbol: 'ETH',
    symbolSpecial: 'ARB',
    chain: CHAIN_ID.arbitrum,
    trcName: 'ETH ERC20 ERC721',
    rpcURL: 'https://open-platform.nodereal.io/ef6556502aac4f22823d07ec697f2477/arbitrum-nitro/',
    scan: 'https://arbiscan.io'
  },
  arbitrumXdai: {
    isL2: true,
    numChainId: 200,
    chainId: '0xC8',

    numLoad: 2,
    isToken: true,
    isSupportedNFT: true,
    trcToken: 'ERC20 AOX',
    nftToken: 'ERC721 AOX',
    balances: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multisend: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    nftMint: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',

    isWeb3: true,
    isFee: true,
    image: 'app_arbitrum_xdai',
    id: 'xdai',
    name: 'Arbitrum on xDai',
    shortName: 'Arbitrum on xDai',
    imageLink: COIN_IMAGE.ETHA0X,
    symbol: 'XDAI',
    symbolSpecial: 'AOX',
    chain: CHAIN_ID.arbitrumXdai,
    trcName: 'XDAI XRC20 XRC721',
    rpcURL: 'https://arbitrum.xdaichain.com',
    scan: 'https://blockscout.com/xdai/aox'
  },
  aurora: {
    isL2: true,
    feeDefault: 0,

    numChainId: 1313161554,
    chainId: '0x4e454152',
    numLoad: 2,
    isToken: true,
    isSupportedNFT: true,
    nftToken: 'AURORA721',
    trcToken: 'AURORA20',
    // balances: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multisend: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    // nftMint: '0xc4cAd0938256ABA4417c565044Be2c2EB77096cb',

    isWeb3: true,
    image: 'app_aurora',

    id: 'aurora-near',
    name: 'Aurora',
    shortName: 'Aurora',
    imageLink: COIN_IMAGE.AURORA,
    symbol: 'AURORA ETH',
    chain: CHAIN_ID.aurora,
    trcName: 'AURORA AURORA20 AURORA721',
    rpcURL: 'https://aurora-mainnet.infura.io/v3/92d53cee52834368b0fabb42fa1b5570',
    scan: 'https://explorer.mainnet.aurora.dev'
  },
  ton: {
    path: "m/44'/501'/0'/0'",
    numPath: 501,
    isMnemonic: true,
    id: 'the-open-network',
    name: 'The Open Network',
    shortName: 'TON',
    imageLink: COIN_IMAGE.TON,
    isToken: false,
    isMemo: true,
    symbol: 'TON',
    chain: CHAIN_ID.ton,
    trcName: 'TON TON721',
    rpcURL: 'https://toncenter.com/api/v2/jsonRPC',
    scan: 'https://tonscan.org',
    image: 'app_ton'
  },
  cronos: {
    id: 'crypto-com-chain',
    chain: CHAIN_ID.cronos,
    name: 'Cronos',
    shortName: 'CRO',
    isToken: true,
    trcToken: 'CRO',
    numChainId: 25,
    chainId: '0x19',
    symbol: 'CRO',
    image: 'app_cronos',
    trcName: 'CRC20 CRC721',
    rpcURL: 'https://evm-cronos.crypto.org',
    scan: 'https://cronoscan.com',
    imageLink: COIN_IMAGE.CRO,
    isSupportedEIP1559: true,
    isSupportedNFT: true,
    isWeb3: true,
    isFee: true,
    balances: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    nftMint: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    multisend: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC'
  },
  bittorrent: {
    numChainId: 199,
    chainId: '0xc7',
    isToken: true,
    trcToken: 'BTT',
    isSupportedNFT: true,
    isWeb3: true,
    isFee: true,
    id: 'bittorrent',
    name: 'BitTorrent Chain',
    shortName: 'BTT',
    image: 'app_bitorrent',
    imageLink: COIN_IMAGE.BTT,
    symbol: 'BTT',
    chain: CHAIN_ID.bittorrent,
    trcName: 'BTT BRC20 BRC721',
    balances: '0x8a77C6d87B5E5Ea7e779C7d14cA50315Bfc4C019',
    nftMint: '0x1C40CBda91e1E0504805eCf038F2e067D11DdBE9',
    multisend: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    rpcURL: 'https://rpc.bt.io',
    scan: 'https://scan.bt.io/#',
    scanTxs: 'transaction',
    scanAddr: 'address'
  },
  theta: {
    path: "m/44'/60'/0'/0/0",
    algo: ALGO.hd,
    numPath: 60,
    trcToken: 'THETA',
    id: 'theta-token',
    name: 'Theta Network',
    shortName: 'THETA',
    image: 'app_thetanetwork',
    imageLink: COIN_IMAGE.THETA,
    symbol: 'THETA',
    chain: CHAIN_ID.theta,
    trcName: 'TNT20 TNT721',
    rpcURL: 'https://theta-bridge-rpc.thetatoken.org/rpc',
    scan: 'https://explorer.thetatoken.org',
    scanTxs: 'txs',
    scanAddr: 'account'
    // isFee: true
  },
  thetaFuel: {
    numChainId: 361,
    chainId: '0x169',
    isToken: true,
    trcToken: 'TFUEL',
    isSupportedNFT: true,
    isWeb3: true,
    isFee: true,
    id: 'theta-fuel',
    name: 'Theta Network EVM',
    shortName: 'THETA',
    image: 'app_thetanetwork',
    imageLink: COIN_IMAGE.TFUEL,
    symbol: 'TFUEL',
    chain: CHAIN_ID.thetaFuel,
    trcName: 'TNT20 TNT721',
    rpcURL: 'https://eth-rpc-api.thetatoken.org/rpc',
    scan: 'https://explorer.thetatoken.org',
    scanTxs: 'txs',
    scanAddr: 'account',
    balances: '0x8a77C6d87B5E5Ea7e779C7d14cA50315Bfc4C019',
    nftMint: '0x1C40CBda91e1E0504805eCf038F2e067D11DdBE9',
    multisend: '0xf7eee3a8363731c611a24cddfcbcade9c153cfe8'
  },
  platon: {
    numChainId: 210425,
    chainId: '0x335F9',
    isToken: true,
    isWeb3: true,
    isFee: true,
    isSupportedNFT: true,
    trcToken: 'LAT',
    id: 'platon-network',
    name: 'PlatON Network',
    shortName: 'LAT',
    image: 'app_platon',
    imageLink: COIN_IMAGE.LAT,
    symbol: 'LAT',
    chain: CHAIN_ID.platon,

    trcName: 'PRC20 PRC721',
    rpcURL: 'https://openapi2.platon.network/rpc',
    scan: 'https://scan.platon.network',
    balances: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    nftMint: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    multisend: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC'
  },
  moonbeam: {
    numChainId: 1284,
    chainId: '0x504',
    isToken: true,
    trcToken: 'GLMR',
    isSupportedEIP1559: true,
    isSupportedNFT: true,
    isWeb3: true,
    isFee: true,
    id: 'moonbeam',
    name: 'Moonbeam',
    shortName: 'GLMR',
    image: 'app_moonbeam',
    imageLink: COIN_IMAGE.GLMR,
    symbol: 'GLMR',
    chain: CHAIN_ID.moonbeam,
    trcName: 'MERC20 MERC721',
    rpcURL: 'https://rpc.api.moonbeam.network',
    scan: 'https://moonscan.io',
    balances: '0x8a77C6d87B5E5Ea7e779C7d14cA50315Bfc4C019',
    nftMint: '0x1C40CBda91e1E0504805eCf038F2e067D11DdBE9',
    multisend: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8'
  },
  aptosLabs: {
    chainId: 'aptoslabs',
    // isToken: true,
    trcToken: 'APT',
    id: 'aptos',
    name: 'Aptos',
    shortName: 'APT',
    image: 'app_aptos',
    imageLink: COIN_IMAGE.APT,
    symbol: 'APT',
    chain: CHAIN_ID.aptosLabs,
    trcName: 'APTOS AIT-3',
    rpcURL: 'https://fullnode.mainnet.aptoslabs.com',
    scan: 'https://tracemove.io',
    scanTxs: 'transaction',
    scanAddr: 'account'
  },
  injective: {
    prefix: 'inj',
    oldNumPath: 118,
    numPath: 60,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'injective-1',
    id: 'injective-protocol',
    name: 'Injective',
    image: 'app_injective',
    symbol: 'INJ',
    imageLink: COIN_IMAGE.INJ,
    chain: CHAIN_ID.injective,
    trcName: 'INJ',
    scan: 'https://www.mintscan.io/injective',
    rpcURL: 'https://tm.injective.network',
    scanTxs: 'txs',
    scanAddr: 'account'
  },
  osmosis: {
    prefix: 'osmo',
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'osmosis-1',
    id: 'osmosis',
    name: 'Osmosis',
    image: 'app_omosis',
    symbol: 'OSMO',
    imageLink: COIN_IMAGE.OSMO,
    chain: CHAIN_ID.osmosis,
    trcName: 'OSMO',
    scan: 'https://www.mintscan.io/osmosis',
    rpcURL: 'https://rpc-osmosis.keplr.app',
    scanTxs: 'txs',
    scanAddr: 'account'
  },
  evmos: {
    prefix: 'evmos',
    oldNumPath: 118,
    numPath: 60,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'evmos_9001-2',
    id: 'evmos',
    name: 'Evmos',
    image: 'app_evmos',
    symbol: 'EVMOS',
    imageLink: COIN_IMAGE.EVMOS,
    chain: CHAIN_ID.evmos,
    trcName: 'EVMOS',
    scan: 'https://www.mintscan.io/evmos',
    rpcURL: 'https://tendermint.bd.evmos.org:26657',
    scanTxs: 'txs',
    scanAddr: 'account',
    isEthermint: true
  },
  juno: {
    prefix: 'juno',
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'juno-1',
    id: 'juno-network',
    name: 'Juno Network',
    image: 'app_juno',
    symbol: 'JUNO',
    imageLink: COIN_IMAGE.JUNO,
    chain: CHAIN_ID.juno,
    trcName: 'JUNO',
    scan: 'https://www.mintscan.io/juno',
    rpcURL: 'https://rpc-osmosis.keplr.app',
    scanTxs: 'txs',
    scanAddr: 'account'
  },
  agoric: {
    prefix: 'agoric',
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'agoric-3',
    id: 'agoric',
    name: 'Agoric',
    image: 'app_agoric',
    symbol: 'BLD',
    imageLink: COIN_IMAGE.BLD,
    chain: CHAIN_ID.agoric,
    trcName: 'BLD',
    scan: 'https://bigdipper.live/agoric',
    rpcURL: 'https://rpc-agoric.keplr.app',
    scanTxs: 'transactions',
    scanAddr: 'accounts'
  },
  oasis: {
    numChainId: 42262,
    chainId: '0xa516',
    numLoad: 0,
    isToken: true,

    trcToken: 'ORC20',
    nftToken: 'ORC721',
    balances: '0x38bb7b9b87bdfbed883aaf50a2f411d330fe32d6',
    multisend: '0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6',

    isWeb3: true,
    isFee: true,
    image: 'app_oasis',
    id: 'oasis-network',
    name: 'Oasis Network',
    shortName: 'ROSE',
    imageLink: COIN_IMAGE.ROSE,
    symbol: 'ROSE',
    chain: CHAIN_ID.oasis,
    trcName: 'ROSE ORC20 ORC721',
    rpcURL: 'https://emerald.oasis.dev',
    scan: 'https://explorer.emerald.oasis.dev/',
    scanTxs: 'tx',
    scanAddr: 'address'
  },
  kujira: {
    prefix: 'kujira',
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'kaiyo-1',
    id: 'kujira',
    name: 'Kujira',
    image: 'app_kujira',
    symbol: 'KUJI',
    imageLink: COIN_IMAGE.KUJI,
    chain: CHAIN_ID.kujira,
    trcName: 'KUJI',
    scan: 'https://www.mintscan.io/kujira',
    rpcURL: 'https://rpc.kaiyo.kujira.setten.io',
    scanTxs: 'txs',
    scanAddr: 'account'
  },
  stargaze: {
    prefix: 'stars',
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'stargaze-1',
    id: 'stargaze',
    name: 'Stargaze',
    image: 'app_stagraze',
    symbol: 'STARS',
    imageLink: COIN_IMAGE.STARS,
    chain: CHAIN_ID.stargaze,
    trcName: 'STARS',
    scan: 'https://www.mintscan.io/stargaze',
    rpcURL: 'https://rpc-stargaze.keplr.app',
    scanTxs: 'txs',
    scanAddr: 'account'
  },
  umee: {
    prefix: 'umee',
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'umee-1',
    id: 'umee',
    name: 'Umee',
    image: 'app_umee',
    symbol: 'UMEE',
    imageLink: COIN_IMAGE.UMEE,
    chain: CHAIN_ID.umee,
    trcName: 'UMEE',
    scan: 'https://www.mintscan.io/umee',
    rpcURL: 'https://rpc-umee.keplr.app',
    scanTxs: 'txs',
    scanAddr: 'account'
  },
  stride: {
    prefix: 'stride',
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'stride-1',
    id: 'stride',
    name: 'Stride',
    image: 'app_stride',
    symbol: 'STRD',
    imageLink: COIN_IMAGE.STRD,
    chain: CHAIN_ID.stride,
    trcName: 'STRD',
    scan: 'https://www.mintscan.io/stride',
    rpcURL: 'https://rpc-stride.keplr.app',
    scanTxs: 'txs',
    scanAddr: 'account'
  },
  baseTest: {
    isToken: true,
    isSupportedNFT: true,

    trcToken: 'ERC20',
    nftToken: 'ERC721',
    trcName: 'ETH ERC20 ERC721',
    environment: 'devnet',
    isDevnet: true,
    numChainId: 84531,
    chainId: '0x14A33',
    numLoad: 2,
    isFee: true,
    isWeb3: true,
    balances: '0x1C40CBda91e1E0504805eCf038F2e067D11DdBE9',
    nftMint: '0xB3E382CA0562C4440f346768b9b20bA813d21FDb',
    multisend: '0x8a77C6d87B5E5Ea7e779C7d14cA50315Bfc4C019',
    name: 'Base',
    image: 'ic-base',
    imageLink: 'COIN_IMAGE.BASE',
    symbol: 'ETH',
    chain: CHAIN_ID.baseTest,
    rpcURL: 'https://goerli.base.org',
    scan: 'https://goerli.basescan.org'
  },
  aptos: {
    environment: 'devnet',
    // isDevnet: true,
    chainId: 'ait-3',
    // isToken: true,
    trcToken: 'APT',
    id: 'aptos-test',
    name: 'Aptos Testnet',
    shortName: 'APT',
    image: 'app_aptos',
    imageLink: COIN_IMAGE.APT,
    symbol: 'APT-TEST',
    chain: CHAIN_ID.aptos,
    trcName: 'APTOS AIT-3',
    rpcURL: 'https://fullnode.testnet.aptoslabs.com',
    scan: 'https://testnet.tracemove.io',
    scanTxs: 'transaction',
    scanAddr: 'account'
  },
  aptosDev: {
    environment: 'devnetFull',
    isDevnet: true,
    chainId: 'ait-dev',
    // isToken: true,
    trcToken: 'APT',
    id: 'aptos-dev',
    name: 'Aptos DevNet',
    shortName: 'APT',
    image: 'app_aptos',
    imageLink: COIN_IMAGE.APT,
    symbol: 'APT-DEV',
    chain: CHAIN_ID.aptosDev,
    trcName: 'APTOS AIT-3',
    rpcURL: 'https://fullnode.devnet.aptoslabs.com',
    scan: 'https://devnet.tracemove.io',
    scanTxs: 'transaction',
    scanAddr: 'account'
  },
  suiMainnet: {
    path: "m/44'/784'/0'/0'/0'",
    numPath: 784,
    chainId: 'sui',
    trcToken: 'SUI',
    id: 'sui',
    name: 'Sui',
    shortName: 'Sui',
    image: 'app_sui',
    imageLink: COIN_IMAGE.SUI,
    symbol: 'SUI',
    chain: CHAIN_ID.sui,
    trcName: 'SUI',
    rpcURL: 'https://wallet-rpc.mainnet.sui.io/',
    scan: 'https://explorer.sui.io',
    scanTxs: 'transactions',
    scanAddr: 'addresses'
  },

  // Old DevNet standard - tempory remove for stable version
  // sui: {
  //   environment: 'devnet',
  //   isDevnet: true,
  //   chainId: 'sui',
  //   trcToken: 'SUI',
  //   id: 'sui',
  //   name: 'Sui',
  //   shortName: 'Sui',
  //   image: 'app_sui',
  //   imageLink: COIN_IMAGE.SUI,
  //   symbol: 'SUI',
  //   chain: CHAIN_ID.sui,
  //   trcName: 'SUI',
  //   rpcURL: 'https://gateway.devnet.sui.io:443',
  //   scan: 'https://explorer.devnet.sui.io',
  //   scanTxs: 'transactions',
  //   scanAddr: 'addresses'
  // },

  sei: {
    prefix: 'sei',
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    // isToken: true,
    isSupportedNFT: true,

    chainId: 'atlantic-2',
    id: 'sei',
    name: 'Sei Testnet',
    image: 'app_sei',
    symbol: 'SEI',
    imageLink: COIN_IMAGE.SEI,
    chain: CHAIN_ID.sei,
    trcName: 'Sei Chain',
    scan: 'https://sei.explorers.guru',
    rpcURL: 'https://rpc.atlantic-2.seinetwork.io/',
    scanTxs: 'transaction',
    scanAddr: 'account'
  },
  archway: {
    prefix: 'archway',
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,
    isDevnet: true,

    chainId: 'constantine-1',
    id: 'constantine-1',
    name: 'Archway',
    image: 'app_archway',
    symbol: 'CONST',
    imageLink: COIN_IMAGE.CONST,
    chain: CHAIN_ID.archway,
    trcName: 'Constantine Testnet',
    scan: 'https://explorer.constantine-1.archway.tech',
    rpcURL: 'https://rpc.constantine-1.archway.tech',
    scanTxs: 'transactions',
    scanAddr: 'account'
  },
  doge: {
    path: "m/44'/3'/0'/0/0",
    // oldNumPath: 0,
    algo: ALGO.hd,
    isEstimateGas: true,

    gasDefault: 0.00009,
    isSupportedNFT: true,
    isCrawlNFTServices: true,

    subName: 'DOGE',
    isHd: true,
    numPath: 0,
    numLoad: 5,
    isFee: true,
    isMnemonic: true,
    image: 'app_doge',
    id: 'dogecoin',
    name: 'Dogecoin',
    shortName: 'dogecoin',
    symbol: 'DOGE',
    chain: CHAIN_ID.doge,
    trcName: 'DOGE',
    scan: 'https://dogechain.info/'
  },
  xrp: {
    path: "m/44'/144'/0'/0/0",
    // oldNumPath: 0,
    algo: ALGO.hd,
    isEstimateGas: true,

    gasDefault: 0.00009,
    isSupportedNFT: true,
    isCrawlNFTServices: true,

    subName: 'DOGE',
    isHd: true,
    numPath: 0,
    numLoad: 5,
    isFee: true,
    isMnemonic: true,
    image: 'app_doge',
    id: 'ripple',
    name: 'Ripple',
    shortName: 'ripple',
    symbol: 'XRP',
    chain: CHAIN_ID.xrp,
    trcName: 'XRP',
    scan: 'https://bithomp.com'
  },
  bitcoinTestNet: {
    path: "m/84'/0'/0'/0/0",
    // oldNumPath: 0,
    algo: ALGO.hd,
    isEstimateGas: true,

    gasDefault: 0.00009,
    isSupportedNFT: true,
    isCrawlNFTServices: true,

    subName: 'BTC',
    isHd: true,
    numPath: 0,
    numLoad: 5,
    isFee: true,
    isMnemonic: true,
    image: 'app_bitcoin',
    id: 'bitcoin',
    name: 'Bitcoin',
    shortName: 'Bitcoin',
    imageLink: COIN_IMAGE.BTC,
    symbol: 'BTC',
    chain: CHAIN_ID.bitcoinTestNet,
    trcName: 'BTC',
    scan: 'https://mempool.space/'
  },
  xion: {
    prefix: 'xion',
    numPath: 118,
    // isToken: true,
    // standard: 'CW20',
    isFactory: true,
    isCosmos: true,
    isMemo: true,

    id: 'terra-luna-2',
    chainId: 'xion-testnet-1',

    name: 'xion-testnet-1',
    icon: 'app_xion',
    symbol: 'XION',
    logo: COIN_IMAGE.LUNA2,
    chain: CHAIN_ID.xion,
    tokenStandard: 'LUNA CW20',
    scan: 'https://finder.terra.money/mainnet'
  }
}

export const stakeAmount = {
  minStakePrice: {
    name: 'minStakePrice',
    pack: 'basic',
    value: [1000, 9999]
  },
  mediumStakePrice: {
    name: 'mediumStakePrice',
    pack: 'standard',
    value: [10000, 99999]
  },
  maxStakePrice: {
    name: 'maxStakePrice',
    pack: 'premium',
    value: [100000, 1000000]
  }
}

export const stakePeriod = {
  minStakeTime: {
    name: 'minStakeTime',
    month: 3,
    value: 7776000 // 3months to timestamps seconds
  },
  mediumStakeTime: {
    name: 'mediumStakeTime',
    month: 6,
    value: 15552000
  },
  maxStakeTime: {
    name: 'maxStakeTime',
    month: 12,
    value: 31104000
  }
}
export const supportURL = 'https://information.coin98.com/api/'

export const USDT_CHAIN = {
  ether: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
  binanceSmart: '0x55d398326f99059fF775485246999027B3197955',
  avax: '0xc7198437980c041c805A1EDcbA50c1Ce5db95118',
  matic: '0xc2132D05D31c914a87C6611C10748AEb04B58e8F',
  celo: '0x765DE816845861e75A25fCA122bb6898B8B1282a',
  kucoin: '0x0039f574eE5cC39bdD162E9A88e3EB1f111bAF48',
  fantom: '0x04068DA6C83AFCFA0e13ba15A6696662335D5B75',
  boba: '0x5DE1677344D3Cb0D7D465c10b72A8f60699C062d',
  heco: '0xa71EdC38d189767582C38A3145b5873052c3e47a'
}

export const unlimitedHex = 'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff'

export const C98_TOKEN = {
  [CHAIN_ID.ether]: {
    name: 'Coin98',
    symbol: 'C98',
    cgkId: 'coin98',
    decimals: 18,
    image: COIN_IMAGE.C98,
    address: '0xAE12C5930881c53715B369ceC7606B70d8EB229f'
  },
  [CHAIN_ID.binanceSmart]: {
    name: 'Coin98',
    symbol: 'C98',
    cgkId: 'coin98',
    decimals: 18,
    image: COIN_IMAGE.C98,
    address: '0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6'
  },
  [CHAIN_ID.matic]: {
    name: 'Coin98',
    symbol: 'C98',
    cgkId: 'coin98',
    decimals: 18,
    image: COIN_IMAGE.C98,
    address: '0x77f56cf9365955486B12C4816992388eE8606f0E'
  },
  [CHAIN_ID.solana]: {
    name: 'Coin98',
    symbol: 'C98',
    cgkId: 'coin98',
    decimals: 6,
    image: COIN_IMAGE.C98,
    address: 'C98A4nkJXhpVZNAZdHUA95RpTF3T4whtQubL3YobiUX9'
  }
}

export const SEND_DATA = {
  send: {
    isToken: true,
    subValue: '-',
    text: 'send',
    color: 'RED',
    icon: 'app_send'
  },
  sendMulti: {
    isToken: true,
    subValue: '-',
    text: 'to',
    color: 'RED',
    icon: 'app_multi_send'
  },
  receive: {
    isToken: true,
    subValue: '+',
    text: 'receive',
    color: 'GREEN',
    icon: 'app_receive'
  },
  createATA: {
    isToken: true,
    subValue: '',
    text: 'initAccount',
    color: 'GREEN',
    icon: 'app_wallet'
  },
  self: {
    isToken: true,
    subValue: '',
    text: 'self',
    color: 'YELLOW',
    icon: 'app_self'
  },
  callContract: {
    subValue: '',
    isNoSubView: true,

    text: 'callContract',
    color: 'YELLOW',
    icon: 'app_call_contract'
  },
  revoked: {
    isToken: true,
    subValue: '',
    text: 'revoked',
    color: 'RED',
    icon: 'app_close_square'
  },
  approval: {
    isToken: true,
    subValue: '',
    text: 'approval',
    color: 'YELLOW',
    icon: 'app_approve'
  },
  fail: {
    isNoSubView: true,
    subValue: '',
    text: 'fail',
    color: 'YELLOW',
    icon: 'app_fail'
  },
  swap: {
    isToken: true,
    subValue: '',
    text: 'swap',
    color: 'YELLOW',
    icon: 'app_swap'
  },
  addLiq: {
    subValue: '',
    text: 'addLiq',
    color: 'YELLOW',
    icon: 'add_liquidity'
  },
  removLiq: {
    subValue: '',
    text: 'removLiq',
    color: 'YELLOW',
    icon: 'app_remove_liquidity'
  },
  vault: {
    subValue: '',
    text: 'vault',
    color: 'YELLOW',
    icon: 'app_vault'
  }
}
